[package]
name = "lexicon"
version = "0.1.0"
edition = "2021"
authors = ["Alvaro Tolentino <alvarotolentinou@gmail.com>"]
description = "An interpreter language written in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
